export const ANIMATION_LIBRARY = [
    { id: "afraid", label: "Afraid", slug: "afraid", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/afraid.avif", category: "gesture" },
    { id: "agree", label: "Agree", slug: "agree", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/agree.avif", category: "gesture" },
    { id: "angry_01", label: "Angry 01", slug: "angry_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/angry_01.avif", category: "gesture" },
    { id: "angry_02", label: "Angry 02", slug: "angry_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/angry_02.avif", category: "gesture" },
    { id: "angry_03", label: "Angry 03", slug: "angry_03", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/angry_03.avif", category: "gesture" },
    { id: "basketball_shot", label: "Basketball Shot", slug: "basketball_shot", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/basketball_shot.avif", category: "other" },
    { id: "bow", label: "Bow", slug: "bow", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/bow.avif", category: "gesture" },
    { id: "box_01", label: "Box 01", slug: "box_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/box_01.avif", category: "other" },
    { id: "box_02", label: "Box 02", slug: "box_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/box_02.avif", category: "other" },
    { id: "box_03", label: "Box 03", slug: "box_03", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/box_03.avif", category: "other" },
    { id: "cast_a_spell", label: "Cast A Spell", slug: "cast_a_spell", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/cast_a_spell.avif", category: "other" },
    { id: "cheer", label: "Cheer", slug: "cheer", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/cheer.avif", category: "other" },
    { id: "chop", label: "Chop", slug: "chop", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/chop.avif", category: "other" },
    { id: "clap", label: "Clap", slug: "clap", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/clap.avif", category: "gesture" },
    { id: "climb", label: "Climb", slug: "climb", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/climb.avif", category: "action" },
    { id: "complain_01", label: "Complain 01", slug: "complain_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/complain_01.avif", category: "other" },
    { id: "complain_02", label: "Complain 02", slug: "complain_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/complain_02.avif", category: "other" },
    { id: "crossover_dribble", label: "Crossover Dribble", slug: "crossover_dribble", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/crossover_dribble.avif", category: "other" },
    { id: "cry", label: "Cry", slug: "cry", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/cry.avif", category: "other" },
    { id: "dance_01", label: "Dance 01", slug: "dance_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_01.avif", category: "dance" },
    { id: "dance_02", label: "Dance 02", slug: "dance_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_02.avif", category: "dance" },
    { id: "dance_03", label: "Dance 03", slug: "dance_03", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_03.avif", category: "dance" },
    { id: "dance_04", label: "Dance 04", slug: "dance_04", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_04.avif", category: "dance" },
    { id: "dance_05", label: "Dance 05", slug: "dance_05", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_05.avif", category: "dance" },
    { id: "dance_06", label: "Dance 06", slug: "dance_06", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dance_06.avif", category: "dance" },
    { id: "defeat", label: "Defeat", slug: "defeat", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/defeat_02.avif", category: "other" },
    { id: "defeat_02", label: "Defeat 02", slug: "defeat_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/defeat_03.avif", category: "other" },
    { id: "depressed", label: "Depressed", slug: "depressed", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/depressed.avif", category: "other" },
    { id: "dig", label: "Dig", slug: "dig", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dig.avif", category: "other" },
    { id: "dive", label: "Dive", slug: "dive", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dive.avif", category: "other" },
    { id: "dribble", label: "Dribble", slug: "dribble", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/dribble.avif", category: "other" },
    { id: "fall", label: "Fall", slug: "fall", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/fall.avif", category: "action" },
    { id: "fire", label: "Fire", slug: "fire", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/fire.avif", category: "other" },
    { id: "flee_01", label: "Flee 01", slug: "flee_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/flee_01.avif", category: "other" },
    { id: "flee_02", label: "Flee 02", slug: "flee_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/flee_02.avif", category: "other" },
    { id: "flip", label: "Flip", slug: "flip", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/flip.avif", category: "other" },
    { id: "fold_arms", label: "Fold Arms", slug: "fold_arms", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/fold_arms.avif", category: "other" },
    { id: "football_catch", label: "Football Catch", slug: "football_catch", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/football_catch.avif", category: "other" },
    { id: "football_save", label: "Football Save", slug: "football_save", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/football_save.avif", category: "other" },
    { id: "football_pass", label: "Football Pass", slug: "football_pass", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/football_pass.avif", category: "other" },
    { id: "freaky", label: "Freaky", slug: "freaky", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/freaky.avif", category: "other" },
    { id: "frightened", label: "Frightened", slug: "frightened", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/frightened.avif", category: "other" },
    { id: "front_kick_01", label: "Front Kick 01", slug: "front_kick_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/front_kick_01.avif", category: "combat" },
    { id: "front_kick_02", label: "Front Kick 02", slug: "front_kick_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/front_kick_02.avif", category: "combat" },
    { id: "frustrated_01", label: "Frustrated 01", slug: "frustrated_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/frustrated_01.avif", category: "other" },
    { id: "frustrated_02", label: "Frustrated 02", slug: "frustrated_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/frustrated_02.avif", category: "other" },
    { id: "greet_01", label: "Greet 01", slug: "greet_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/greet_01.avif", category: "other" },
    { id: "greet_02", label: "Greet 02", slug: "greet_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/greet_02.avif", category: "other" },
    { id: "greet_03", label: "Greet 03", slug: "greet_03", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/greet_03.avif", category: "other" },
    { id: "greet_04", label: "Greet 04", slug: "greet_04", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/greet_04.avif", category: "other" },
    { id: "heart_pose", label: "Heart Pose", slug: "heart_pose", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/heart_pose.avif", category: "other" },
    { id: "hit_to_body_01", label: "Hit To Body 01", slug: "hit_to_body_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hit_to_body_01.avif", category: "combat" },
    { id: "hit_to_body_02", label: "Hit To Body 02", slug: "hit_to_body_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hit_to_body_02.avif", category: "combat" },
    { id: "hit_to_head", label: "Hit To Head", slug: "hit_to_head", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hit_to_head.avif", category: "combat" },
    { id: "hit_to_side", label: "Hit To Side", slug: "hit_to_side", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hit_to_side.avif", category: "combat" },
    { id: "hit_to_stomach", label: "Hit To Stomach", slug: "hit_to_stomach", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hit_to_stomach.avif", category: "combat" },
    { id: "hug", label: "Hug", slug: "hug", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/hug.avif", category: "other" },
    { id: "idle", label: "Idle", slug: "idle", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/idle.avif", category: "idle" },
    { id: "jump_down", label: "Jump Down", slug: "jump_down", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/jump_down.avif", category: "action" },
    { id: "jump", label: "Jump", slug: "jump", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/jump.avif", category: "action" },
    { id: "jump_rope_01", label: "Jump Rope 01", slug: "jump_rope_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/jump_rope_01.avif", category: "action" },
    { id: "jump_rope_02", label: "Jump Rope 02", slug: "jump_rope_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/jump_rope_02.avif", category: "action" },
    { id: "laugh_01", label: "Laugh 01", slug: "laugh_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/laugh_01.avif", category: "other" },
    { id: "laugh_02", label: "Laugh 02", slug: "laugh_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/laugh_02.avif", category: "other" },
    { id: "lift_heavy", label: "Lift Heavy", slug: "lift_heavy", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/lift_heavy.avif", category: "other" },
    { id: "look_around", label: "Look Around", slug: "look_around", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/look_around.avif", category: "other" },
    { id: "make_a_call_01", label: "Make A Call 01", slug: "make_a_call_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/make_a_call_01.avif", category: "other" },
    { id: "make_a_call_02", label: "Make A Call 02", slug: "make_a_call_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/make_a_call_02.avif", category: "other" },
    { id: "pitch_baseball", label: "Pitch Baseball", slug: "pitch_baseball", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/pitch_baseball.avif", category: "other" },
    { id: "play_mobile_game", label: "Play Mobile Game", slug: "play_mobile_game", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/play_mobile_game.avif", category: "other" },
    { id: "play_video_game", label: "Play Video Game", slug: "play_video_game", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/play_video_game.avif", category: "other" },
    { id: "press-up", label: "Press Up", slug: "press-up", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/press-up.avif", category: "other" },
    { id: "run_upstairs", label: "Run Upstairs", slug: "run_upstairs", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/run_upstairs.avif", category: "running" },
    { id: "run", label: "Run", slug: "run", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/run.avif", category: "running" },
    { id: "scared_01", label: "Scared 01", slug: "scared_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/scared_01.avif", category: "other" },
    { id: "scared_02", label: "Scared 02", slug: "scared_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/scared_02.avif", category: "other" },
    { id: "scratch", label: "Scratch", slug: "scratch", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/scratch.avif", category: "other" },
    { id: "shoot", label: "Shoot", slug: "shoot", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/shoot.avif", category: "combat" },
    { id: "shovel", label: "Shovel", slug: "shovel", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/shovel.avif", category: "other" },
    { id: "sing_01", label: "Sing 01", slug: "sing_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sing_01.avif", category: "other" },
    { id: "sing_02", label: "Sing 02", slug: "sing_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sing_02.avif", category: "other" },
    { id: "sing_03", label: "Sing 03", slug: "sing_03", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sing_03.avif", category: "other" },
    { id: "sing_04", label: "Sing 04", slug: "sing_04", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sing_04.avif", category: "other" },
    { id: "sit", label: "Sit", slug: "sit", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sit.avif", category: "action" },
    { id: "slash", label: "Slash", slug: "slash", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/slash.avif", category: "other" },
    { id: "sob", label: "Sob", slug: "sob", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/sob.avif", category: "other" },
    { id: "standing_relax", label: "Standing Relax", slug: "standing_relax", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/standing_relax.avif", category: "idle" },
    { id: "surf", label: "Surf", slug: "surf", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/surf.avif", category: "other" },
    { id: "swagger", label: "Swagger", slug: "swagger", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/swagger.avif", category: "other" },
    { id: "swim", label: "Swim", slug: "swim", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/swim.avif", category: "action" },
    { id: "turn", label: "Turn", slug: "turn", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/turn.avif", category: "other" },
    { id: "volleyball", label: "Volleyball", slug: "volleyball", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/volleyball.avif", category: "other" },
    { id: "wait", label: "Wait", slug: "wait", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/wait.avif", category: "other" },
    { id: "walk", label: "Walk", slug: "walk", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/walk.avif", category: "walking" },
    { id: "warm_up", label: "Warm Up", slug: "warm_up", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/warm_up.avif", category: "other" },
    { id: "wave_goodbye_01", label: "Wave Goodbye 01", slug: "wave_goodbye_01", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/wave_goodbye_01.avif", category: "gesture" },
    { id: "wave_goodbye_02", label: "Wave Goodbye 02", slug: "wave_goodbye_02", gif: "https://tripo-public.tripo3d.ai/studio_riging_data/biped/wave_goodbye_02.avif", category: "gesture" },
];
export const ANIM_CATEGORIES = ['all', 'walking', 'running', 'idle', 'dance', 'gesture', 'combat', 'action', 'other'];

export const getAnimById = (id) => ANIMATION_LIBRARY.find((a) => a.id === id);
export const getAnimsByCategory = (cat) => cat === 'all' ? ANIMATION_LIBRARY : ANIMATION_LIBRARY.filter((a) => a.category === cat);






